# Generated by Django 5.0 on 2024-08-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_order_address_alter_order_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(choices=[('PAID', 'paid'), ('NOT_PAID', 'not_paid')], default=False),
        ),
    ]
