# Generated by Django 5.0 on 2024-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(choices=[('PAID', 'paid'), ('NOT_PAID', 'not_paid')], default='NOT_PAID'),
        ),
    ]
