# Generated by Django 5.0 on 2024-08-17 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_order_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(choices=[('NOT_PAID', 'not_paid'), ('PAID', 'paid')], default='NOT_PAID'),
        ),
    ]
