# Generated by Django 5.0 on 2024-04-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gallerytwo',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
