# Generated by Django 5.0 on 2024-04-28 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_gallery_name_alter_gallerytwo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gallerytwo',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
