# Generated by Django 5.0 on 2024-05-02 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_gallery_name_alter_gallerytwo_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerytwo',
            name='title',
        ),
    ]
