# Generated by Django 5.0 on 2024-05-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
