# Generated by Django 5.0 on 2024-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0004_certificatestitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificatestitle',
            name='title',
            field=models.TextField(blank=True),
        ),
    ]
