# Generated by Django 5.0 on 2024-05-02 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0005_alter_certificatestitle_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
