# Generated by Django 5.0 on 2024-05-02 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0006_rename_certificates_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificate',
            new_name='Certificates',
        ),
    ]
