# Generated by Django 5.0 on 2024-05-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_rename_certificate_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatesimages',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
