# Generated by Django 5.0 on 2024-09-06 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
    ]
